/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionpanels;

import data.Function;
import data.Phase;

/**
 *
 * @author Ries
 */
public class EmptyFunctionPanel extends FunctionPanel {

    /**
     * Creates new form RateFunctionPanel
     */
    public EmptyFunctionPanel() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jLabel_nosettings = new javax.swing.JLabel();

        jLabel_nosettings.setText("No settings");
        jLabel_nosettings.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel_nosettings)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel_nosettings)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_nosettings;
    // End of variables declaration//GEN-END:variables
	@Override

	public void setInstructions() {}

	@Override
	public void setPossibleFunctions() {
		possibleFunction = new String[4];
		possibleFunction[0] = Function.STP.getName();
		possibleFunction[1] = Function.PRL.getName();
		possibleFunction[2] = Function.PRI.getName();
		possibleFunction[3] = Function.BEP.getName();
	}

	@Override
	public void setPhase(Phase p) {
		this.currentphase = p;
	}

	@Override
	public void updatePhase() {}
}
