/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionpanels;

import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import data.Function;
import data.Phase;

/**
 *
 * @author Ries
 */
public class LoopToPreviousFunctionPanel extends FunctionPanel {

    /**
     * Creates new form RateFunctionPanel
     */
    public LoopToPreviousFunctionPanel() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jLabel_loop = new javax.swing.JLabel();
        SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, 99, 1);  
        jSpinner_phase = new javax.swing.JSpinner(model1);
        jSpinner_phase.addChangeListener(new ChangeListener() {      
			@Override
			public void stateChanged(ChangeEvent arg0) {
				updatePhase();
			}
        });
        jLabel_times = new javax.swing.JLabel();

        jLabel_loop.setText("Loop to previous loop:");

        jLabel_times.setText("times");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_loop)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSpinner_phase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_times)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_loop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_phase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_times))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_loop;
    private javax.swing.JLabel jLabel_times;
    private javax.swing.JSpinner jSpinner_phase;
    // End of variables declaration//GEN-END:variables
	@Override
	public void setPhase(Phase p) {
		if(p.getFunction().equals(possibleFunction[0]) || p.getFunction().equals(possibleFunction[1])){
			this.currentphase = p;
			int param=0;
			try{
				param = Integer.parseInt(p.getCommand().substring(3, 2));
			} catch (Exception e){}
			jSpinner_phase.setValue(param);
		}
	}

	@Override
	public void updatePhase() {
		this.currentphase.setParameter(String.valueOf((Integer) jSpinner_phase.getValue()));		
	}

	@Override
	public void setInstructions() {	}

	@Override
	public void setPossibleFunctions() {
		possibleFunction = new String[2];
		possibleFunction[1] = Function.LOP.getName();
		possibleFunction[0] = Function.LPE.getName();
	}
}
