/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionpanels;

import data.Function;
import data.Phase;

/**
 *
 * @author Ries
 */
public class OutFunctionPanel extends FunctionPanel {

    /**
     * Creates new form RateFunctionPanel
     */
    public OutFunctionPanel() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        jLabel_out = new javax.swing.JLabel();
        jComboBox_out = new javax.swing.JComboBox();

        jLabel_out.setText("OUT signal:");

        jComboBox_out.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel_out)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_out)
                    .addComponent(jComboBox_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_out;
    private javax.swing.JLabel jLabel_out;
    // End of variables declaration//GEN-END:variables
	@Override
	public void setPhase(Phase p) {
		if(p.getFunction().equals(possibleFunction[0])){
			this.currentphase = p;
			int param=0;
			try{
				param = Integer.parseInt(p.getCommand().substring(3, 1));
			} catch (Exception e){}
			if(param==0 || param ==1){
				jComboBox_out.setSelectedIndex(param);
			}
		}
	}

	@Override
	public void updatePhase() {
		this.currentphase.setParameter(String.valueOf(jComboBox_out.getSelectedIndex()));		
	}

	@Override
	public void setInstructions() {}

	@Override
	public void setPossibleFunctions() {
		possibleFunction = new String[1];
		possibleFunction[0] = Function.OUT.getName();
	}
}
