/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionpanels;

/**
 *
 * @author Ries
 */
public class PauseFunctionPanel extends javax.swing.JPanel {

    /**
     * Creates new form RateFunctionPanel
     */
    public PauseFunctionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_pause = new javax.swing.JLabel();
        jLabel_format = new javax.swing.JLabel();
        jComboBox_format = new javax.swing.JComboBox();
        jTextField_pause = new javax.swing.JTextField();

        jLabel1_pause.setText("Pause (s):");

        jLabel_format.setText("Format:");

        jComboBox_format.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nn", "n.n" }));

        jTextField_pause.setText("34");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1_pause)
                    .addComponent(jLabel_format))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_format, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_pause))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_format)
                    .addComponent(jComboBox_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_pause)
                    .addComponent(jTextField_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_format;
    private javax.swing.JLabel jLabel1_pause;
    private javax.swing.JLabel jLabel_format;
    private javax.swing.JTextField jTextField_pause;
    // End of variables declaration//GEN-END:variables
}
