/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionpanels;

/**
 *
 * @author Ries
 */
public class RateFunctionPanel extends javax.swing.JPanel {

    /**
     * Creates new form RateFunctionPanel
     */
    public RateFunctionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_rate = new javax.swing.JLabel();
        jTextField_rate = new javax.swing.JTextField();
        jComboBox_time = new javax.swing.JComboBox();
        jTextField_time = new javax.swing.JTextField();
        jLabel_time = new javax.swing.JLabel();
        jToggleButton_withdraw = new javax.swing.JToggleButton();
        jToggleButton_infuse = new javax.swing.JToggleButton();

        jLabel_rate.setText("Rate (uL/mn):");

        jTextField_rate.setText("300");

        jComboBox_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "h", "min", "sec" }));

        jTextField_time.setText("65");

        jLabel_time.setText("Time:");

        jToggleButton_withdraw.setText("<");

        jToggleButton_infuse.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_rate)
                    .addComponent(jLabel_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton_withdraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton_infuse))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_time)
                            .addComponent(jTextField_rate))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_rate)
                    .addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_time)
                    .addComponent(jTextField_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_withdraw)
                    .addComponent(jToggleButton_infuse)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_time;
    private javax.swing.JLabel jLabel_rate;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JTextField jTextField_rate;
    private javax.swing.JTextField jTextField_time;
    private javax.swing.JToggleButton jToggleButton_infuse;
    private javax.swing.JToggleButton jToggleButton_withdraw;
    // End of variables declaration//GEN-END:variables
}
